# Generated by Django 6.0.2 on 2026-03-01 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата лайка')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AlterModelOptions(
            name='viewstat',
            options={'ordering': ['-viewed_at'], 'verbose_name': 'Статистика просмотра', 'verbose_name_plural': 'Статистика просмотров'},
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, help_text='Длительность видео в секундах', verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='video',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.AddField(
            model_name='video',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, verbose_name='Разрешение'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_format',
            field=models.CharField(blank=True, max_length=10, verbose_name='Формат видео'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-uploaded_at'], name='videos_vide_uploade_5065e7_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploaded_by'], name='videos_vide_uploade_f15265_idx'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('video', 'user')},
        ),
    ]
