# Generated by Django 6.0.2 on 2026-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL'),
        ),
    ]
