# Generated by Django 6.0.2 on 2026-03-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.CharField(blank=True, editable=False, max_length=20, verbose_name='Video ID'),
        ),
    ]
