# Generated by Django 6.0.2 on 2026-03-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_remove_video_slug_video_vid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Video ID'),
        ),
    ]
