# Generated by Django 6.0.2 on 2026-03-01 15:29

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=accounts.models.avatar_upload_path, verbose_name='Аватар')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Баннер')),
                ('bio', models.TextField(blank=True, max_length=1000, verbose_name='О себе')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('subscribers_count', models.PositiveIntegerField(default=0, verbose_name='Подписчики')),
                ('videos_count', models.PositiveIntegerField(default=0, verbose_name='Видео')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотры')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('show_subscribers', models.BooleanField(default=True, verbose_name='Показывать подписчиков')),
                ('show_views', models.BooleanField(default=True, verbose_name='Показывать просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'unique_together': {('subscriber', 'channel')},
            },
        ),
    ]
